### ISSUE TITLE
[Request dependency] PowerShell

### ISSUE THREAD

**Issue by Revival8697** [bottlesdevs/dependencies#126]
**Dependency name**: PowerShell

**Official link to the download page:** https://github.com/PowerShell/PowerShell/releases/latest

**Is this dependency compatible with Wine?**
- [x] Yes: [PowerShell-6.1.6-win-x64.msi](https://github.com/PowerShell/PowerShell/releases/download/v6.1.6/PowerShell-6.1.6-win-x64.msi)
- [ ] Yes, but need tweaks.
- [x] No: Latest x64 MSI, x86 MSI; Pre-release x64 MSI.
- [ ] I have not tested.

**Useful links**
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows

**Comment by mactan-sc** [comment]
powershell verb was recently added to winetricks https://github.com/Winetricks/winetricks/pull/2211

would be good have so that it could be included on the Star Citizen installer as its game launcher relies on powershell for certain actions https://github.com/bottlesdevs/programs/blob/main/Games/starcitizen.yml

**Comment by Vingian** [comment]
https://github.com/bottlesdevs/dependencies/pull/251

**Comment by robert-ulrich-hofmann** [comment]
It seems this was resolved, can we close this issue?
