### ISSUE TITLE
[Report] arial32 font download failed 

### ISSUE THREAD

**Issue by RyuKay24** [bottlesdevs/dependencies#232]
**Which dependency?**
arial32

**Problem type**
- download failed/broken url

**Describe the problem**
arial32 font unable to download due to broken link or server down
error: Failed to download [https://cfhcable.dl.sourceforge.net/project/corefonts/the%20fonts/final/arial32.exe]

**Comment by AlmAck** [comment]
Same, to me the correct link is:

**Comment by Leonidas300** [comment]
I download all fonts separatly, arial32 and trebuc32 have wrong url.

**Comment by xioren** [comment]
The problem is that ```https://sourceforge.net/projects/corefonts/files/the%20fonts/final/arial32.exe``` is a link to the download page, not the download itself. When accessing that page in a browser it loads html and triggers a download after a brief delay. In my case the actual download link was ```https://versaweb.dl.sourceforge.net/project/corefonts/the%20fonts/final/arial32.exe?viasf=1```. This is where the original urls we had came from. However since they are hard-coded if the url structure/server changes the download url breaks, such as in this case.

With that being said I just tested ```https://sourceforge.net/projects/corefonts/files/the%20fonts/final/arial32.exe``` out with ```requests``` (which is what we use internally) and it seems like it redirects properly so I have made a [PR](https://github.com/bottlesdevs/dependencies/pull/233) to update all sourceforge urls.

**Comment by cadecomposer** [comment]
Sorry not sure if this is the right place to ask this, but is there a workaround to be able to make a new bottle in the meantime before this fix gets pushed out in the next release? Was going to set up bottles today after distro hopping, but I've not been able to make a new bottle because it errors out when trying to download the Arial font

**Comment by atuleu** [comment]
> Sorry not sure if this is the right place to ask this, but is there a workaround to be able to make a new bottle in the meantime before this fix gets pushed out in the next release? Was going to set up bottles today after distro hopping, but I've not been able to make a new bottle because it errors out when trying to download the Arial font

I managed to do the following (using flatpak)
```bash
cd <somewhere>
git clone https://github.com/xioren/dependencies.git
```
The repo above is the repo with the PR that sets the right URL for the fonts

If you are using flatpak, with flatseal modify the permission of bottles
* allow bottles to access <somewhere>/dependencies
* add the following env variable `LOCAL_DEPENDENCIES=<somewhere>/dependencies`

To check that it works launch bottles from command line:
```bash
flatpak run com.usebottles.bottles
```

You should see the following log line:
```
(INFO) Using local dependencies repository at <somewhere>/dependencies
```
