### ISSUE TITLE
[Request dependency] Quartz

### ISSUE THREAD

**Issue by kozross** [bottlesdevs/dependencies#67]
**Dependency name**: quartz

**Official link to the download page (not direct download)** https://www.dlldownloader.com/quartz-dll/ (I think, it's a bit hard to find)

**Is this dependency compatible with Wine?**
- [X] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**

* [Winetricks verb list containing quartz](https://github.com/Winetricks/winetricks/blob/master/files/verbs/all.txt).
* [Winetricks implementation](https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L11912). This uses a much older version than the one linked above, though.
* [Why I need it](https://github.com/ValveSoftware/Proton/issues/1048#issuecomment-508674889).

**Comment by mirkobrombin** [comment]
Thanks for reporting

**Comment by tiziodcaio** [comment]
https://docs.microsoft.com/en-us/windows/win32/directshow/directshow
Try installing dirac?

**Comment by kozross** [comment]
> https://docs.microsoft.com/en-us/windows/win32/directshow/directshow Try installing dirac?

Doesn't solve the problem I need quartz for.

**Comment by mirkobrombin** [comment]
Locked by https://github.com/bottlesdevs/Bottles/issues/1485

**Comment by xrishox** [comment]
it looks like the blocker has been closed. is any reason that quartz still can't be added?

**Comment by niedzielski** [comment]
+1, I'm trying to install a different program that [reports claim Quartz is a dependency of](https://appdb.winehq.org/objectManager.php?sClass=version&iId=40005).

**Comment by keenanweaver** [comment]
It's easy enough to make a manifest for quartz.dll based on how Winetricks does it, but it uses such an old version of the DLL. The dxnt.tar.xz in the directplay dependency has quartz.dll, but it is positively ancient (2003).

Regarding the link in the OP, those DLLs are older compared to what's in Windows 11, but newer than what's in Winetricks. It would be nice to have multiple manifests for users to choose which version of a DLL they need instead of a monolithic 'quartz' dependency. Maybe a game works better with an older one instead of the newest. Bottles dependencies should easily allow for users to test.

@mirkobrombin Is it in the cards for Bottles to host dependencies? Seems beneficial to gather up the most common MS components and put them in a centralized spot for use in manifests. Unsure how legally gray that is.

**Comment by niedzielski** [comment]
Did this change go out? I'm on Bottles 2022.9.28.1 but don't see it. From the PR, it looks like it should appear as "directshow" just below the directmusic entry. Thank you!

![image](https://user-images.githubusercontent.com/1071806/194638014-105983f7-8c80-4628-8b60-952095bc7529.png)
